FROM osrf/ros:melodic-desktop-full

RUN apt-get update && apt-get install -y apt-utils build-essential psmisc vim-gtk
RUN rm /bin/sh && ln -s /bin/bash /bin/sh

RUN apt-get update && apt-get install -q -y python-catkin-tools
RUN apt-get update && apt-get install -q -y ros-melodic-hector-gazebo-plugins
RUN python -m pip install --upgrade pip
RUN pip install -r requirements.txt

#COPY this is where the catkin_ws file should be copied into the directory as well as any other materials
#EXPOSE any appropriate ports to communicate to wheelchair need to be exposed here
#ENTRYPOINT the file within the ROS system that needs to be activated
CMD ["bash"] #not sure if this is necessary for our purposes
