footprint: [[0.8, 0.32], [0.8, -0.32], [-0.2, -0.32], [-0.2, 0.32]]
footprint_padding: .1

robot_base_frame: base_link
update_frequency: 5.0
publish_frequency: 10.0
transform_tolerance: 1

resolution: 0.05

obstacle_range: 5.5
raytrace_range: 6.0

#layer definitions
static:
    map_topic: map
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: laser_scan_sensor
    laser: {sensor_frame: laser, data_type: LaserScan, clearing: true, marking: true, topic: scan, inf_is_valid: true}

inflation:
    inflation_radius: 1.0
    cost_scalling_factor: 75
